name: llm-query-expansion-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools
  - wheel
  
  # PyTorch ecosystem (CPU-only)
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - cpuonly
  
  # Scientific computing
  - numpy=1.24.4
  - pandas=2.1.4
  - scipy
  - scikit-learn
  
  # System utilities
  - psutil=5.9.6
  - pyyaml=6.0.1
  - requests=2.31.0
  
  # Development tools
  - jupyter
  - ipykernel
  - black
  - flake8
  - pytest
  
  # AWS CLI
  - awscli
  
  # Pip dependencies
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - pydantic==2.5.0
    - pydantic-settings==2.1.0
    - transformers==4.36.2
    - accelerate==0.25.0
    - bitsandbytes==0.41.3.post2
    - sentencepiece==0.1.99
    - tokenizers==0.15.0
    - boto3==1.34.34
    - botocore==1.34.34
    - mlflow==2.9.2
    - prometheus-client==0.19.0
    - httpx==0.25.2
    - orjson==3.9.10
    - python-multipart==0.0.6
    - optimum[onnxruntime]==1.16.2
    - onnx==1.15.0
    - onnxruntime==1.16.3
    - huggingface-hub==0.19.4