version: '3.8'

services:
  mlflow-db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow-server:
    image: python:3.9-slim
    command: >
      bash -c "
        pip install mlflow psycopg2-binary boto3 &&
        mlflow server 
        --backend-store-uri postgresql://mlflow:mlflow@mlflow-db:5432/mlflow
        --default-artifact-root s3://your-mlflow-artifacts-bucket/artifacts
        --host 0.0.0.0
        --port 5000
      "
    ports:
      - "5000:5000"
    depends_on:
      - mlflow-db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

volumes:
  mlflow_db_data: